### ISSUE TITLE
Stream generation for air - cas_id references different chemical and H_reactive is attempted to use in calculation, but is None

### ISSUE THREAD

**Issue by mikeyj777** [CalebBell/thermo#143] opened 2023-09-27 20:26 UTC
creating Stream to represent air:

s = Stream(IDs = ['132259-10-0'], ws=[1], m=0.27, T=298.15, P=101325)

During instantiation, Stream.set_extensive_properties() is called.

stream.py, line 1909: self.energy_reactive = self.H_reactive*self.m, the self.H_reactive property is None.  Throws error.

stream.name is listed as "(2r)-4-methyl-2-(propan-2-yl)-2-[2-(4-{4-[2-(3,4,5-trimethoxyphenyl)ethyl]piperazin-1-yl}butoxy)phenyl]-2h-1,4-benzothiazin-3(4h)-one dihydrochloride"

**Comment by CalebBell** [comment] 2023-09-29 04:46
Hi mikeyj777,

Looks like an issue in the pubchem metadata. I took a selection of it over 10 years ago and the issue is still there: https://pubchem.ncbi.nlm.nih.gov/#query=132259-10-0
Unfortunately I can't maintain that data since I took ~70000 elements from it and the Stream interface is outdated so I am closing this issue. If what you want to do is model the properties of air, please see the Phase and Flash interface and this example: https://thermo.readthedocs.io/Examples/Creating%20Nitrogen%2C%20oxygen%2C%20and%20nitrogen%20ternary%20air%20system%20phase%20envelope.html

Sincerely,
Caleb

**Closed by CalebBell** 2023-09-29 04:46 UTC

**Comment by mikeyj777** [comment] 2023-10-09 15:43
thank you for getting back to me!  I used nitrogen in place of air, so should be a suitable substitution.
